nodeLinker: node-modules

# Uncomment to use local NPM registry (verdaccio)
# npmRegistryServer: "http://localhost:4873"
# unsafeHttpWhitelist:
#   - localhost

yarnPath: .yarn/releases/yarn-4.1.0.cjs
